### ISSUE TITLE
README File

### ISSUE THREAD

**Issue by Asmaathabet** [Asmaathabet/HotMeal#1]
## Notes to make it better :
- project aim - Introduction - [needed] 
- Team Names
- Table of contents
- main problem 
- problem causes 
- our solution [needed]
- user story 
- user journey 
- Illustrations 
   1- Databases Schema [needed]
   2- Prototype [link] 
- Technologies [needed]
- Launch [needed]
- Project status [needed]
- sources [needed ]

**Comment by czegevarra** [comment]
Hello! My name is Nick, I want to help you with future Readme.
